#pragma config(Motor,  port1,           BL,            tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           FL,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           FR,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          BR,            tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//FOR ROBOT 2 //

#define downPOS 4095
#define upPOS 3483
#define chuckPOS 2355
#define pushPOS 3150
#define clawOPEN 1548
#define clawCLOSE 270

// Controller 1/2, Stick L/R, Axis X/Y
#define C1RY						                vexRT[Ch2]
#define C1LY						                vexRT[Ch3]
#define C1RX							              vexRT[Ch1]
#define C1LX								            vexRT[Ch4]

//Manage Dragon Drive
task DragonDrive()
{
	//Create "deadzone" variables.
	int LY1 = 0, LX1 = 0, RX1 = 0, threshold = 30;

	while(true)
	{
		//Drive Deadzone
		if(abs(C1LY) > threshold){
			LY1 = C1LY;
		}
		else{
			LY1 = 0;
		}
		if(abs(C1RX) > threshold){
			RX1 = C1RX;
		}
		else{
			RX1 = 0;
		}
		if(abs(C1LX) > threshold){
			LX1 = C1LX;
		}
		else{
			LX1 = 0;
		}
		//Send Power to Motor
		motor[FL] = LY1+LX1;
		motor[BL] = LY1+LX1;
		motor[FR] = LY1-LX1;
		motor[BR] = LY1-LX1;
		// Motor values can only be updated every 20ms
		wait1Msec(20);
	}
}

task main()
{
	startTask(DragonDrive);
	while (true)
	{
		// Motor values can only be updated every 20ms
		wait1Msec(20);
	}
}
