#pragma config(Sensor, in1,    POT,            sensorPotentiometer)
#pragma config(Sensor, in2,    POTCLAW,        sensorPotentiometer)
#pragma config(Motor,  port1,           BL,            tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           FL,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           LARMA,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           LARMB,         tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           RARMA,         tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port6,           RARMB,         tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port7,           CLAW1,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           CLAW2,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           FR,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          BR,            tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//FOR ROBOT 2 //

#define downPOS 4095
#define upPOS 3407
#define chuckPOS 1800
#define pushPOS 3160

#define clawOPEN 3379
#define clawCLOSE 315

// Controller 1/2, Stick L/R, Axis X/Y
#define C1RY						                vexRT[Ch2]
#define C1LY						                vexRT[Ch3]
#define C1RX							              vexRT[Ch1]
#define C1LX								            vexRT[Ch4]

int armMode = 0;
int clawMode = 0;
float armTarget;
float clawTarget;

//Task to Manage Claw Position
task runClaw()
{
	clawTarget = clawCLOSE;
	float proportionalCoefficient = 0.35;
	float error,
	motorPower,
	proportional; //what you set the motors to
	while (true)
	{
		//ENABLE PID
		if(clawMode==1){
			error = clawTarget - SensorValue[POTCLAW];
			proportional = error * proportionalCoefficient;
			motorPower = proportional;
			motor[CLAW1] = -motorPower;
			motor[CLAW2] = -motorPower;
		}
		//DISABLE PID
		else if(clawMode==0){
			//Claw Open
			if(vexRT[Btn6U] == 1)
			{
				motor[CLAW1] = 75;
				motor[CLAW2] = 75;
			}
			//Claw Close
			else if(vexRT[Btn6D] == 1)
			{
				motor[CLAW1] = -75;
				motor[CLAW2] = -75;
			}
			//Claw Stop
			else{
				clawTarget = SensorValue[POTCLAW];
				clawMode = 1;
			}
			// Motor values can only be updated every 20ms
			wait1Msec(20);
		}
	}
}

//Task to Manage Arm Position
task runArm()
{
	armTarget = downPOS;
	float proportionalCoefficient = 0.3;
	float error,
	motorPower,
	proportional; //what you set the motors to
	while (true)
	{
		//ENABLE PID
		if(armMode==1){
			error = armTarget - SensorValue[POT];
			proportional = error * proportionalCoefficient;
			motorPower = proportional;
			motor[RARMA] = motorPower;
			motor[RARMB] = motorPower;
			motor[LARMA] = motorPower;
			motor[LARMB] = motorPower;
		}
		//DISABLE PID
		else if(armMode==0){
			//Arm UP
			if(vexRT[Btn5U] == 1)
			{
					motor[RARMA] = -70;
					motor[RARMB] = -70;
					motor[LARMA] = -70;
					motor[LARMB] = -70;
			}
			//Arm Down
			else if(vexRT[Btn5D] == 1)
			{
					motor[RARMA] = 70;
					motor[RARMB] = 70;
					motor[LARMA] = 70;
					motor[LARMB] = 70;
			}
			//Arm Stop
			else{
				armTarget = SensorValue[POT];
				armMode = 1;
			}
			// Motor values can only be updated every 20ms
			wait1Msec(20);
		}
	}
}


//Manage Dragon Drive
task DragonDrive()
{
	//Create "deadzone" variables.
	int LY1 = 0, LX1 = 0, RX1 = 0, RY1= 0, threshold = 30;

	while(true)
	{
		//Drive Deadzone
		if(abs(C1LY) > threshold){
			LY1 = C1LY;
		}
		else{
			LY1 = 0;
		}
		if(abs(C1RX) > threshold){
			RX1 = C1RX;
		}
		else{
			RX1 = 0;
		}
		if(abs(C1LX) > threshold){
			LX1 = C1LX;
		}
		else{
			LX1 = 0;
		}
		if(abs(C1RY) > threshold){
			RY1 = C1RY;
		}
		else{
			RY1 = 0;
		}
		//Send Power to Motor
		//motor[FL] = LY1+LX1;
		//motor[BL] = LY1+LX1;
		//motor[FR] = LY1-LX1;
		//motor[BR] = LY1-LX1;
		motor[FL] = LY1;
		motor[BL] = -LY1;
		motor[FR] = RY1;
		motor[BR] = -RY1;
		// Motor values can only be updated every 20ms
		wait1Msec(20);
	}
}

task main()
{
	startTask(DragonDrive);
	startTask(runArm);
	startTask(runClaw);
	while (true)
	{
		//Move Arm
		if(vexRT[Btn5U] == 1)
		{
			armMode = 0;
		}
		else if(vexRT[Btn5D] == 1)
		{
			armMode = 0;
		}

		//Move Claw
		if(vexRT[Btn6U] == 1)
		{
			clawMode = 0;
		}
		else if(vexRT[Btn6D] == 1)
		{
			clawMode = 0;
		}

		// Motor values can only be updated every 20ms
		wait1Msec(20);
	}
}
