#pragma config(Sensor, in1,    POT,            sensorPotentiometer)
#pragma config(Sensor, in2,    GYRO,           sensorNone)
#pragma config(Motor,  port2,           ARMA,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           ARMB,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           FR,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           BR,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           FL,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           BR,            tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Controller 1/2, Stick L/R, Axis X/Y
#define C1LX vexRT[Ch4]
#define C1LY vexRT[Ch3]
#define C1RX vexRT[Ch1]
#define ARMUP vexRT[Btn6U]
#define ARMDOWN vexRT[ChBtn6D]

//const float TICKS_PER_ROT = 2800; // 2800 ticks for 360 degrees

task main()
{
 clearDebugStream();

 while (true)
    {
    // update data
    writeDebugStreamLine("Value: %d ", SensorValue[POT]);
    }

}
