#pragma config(Motor,  port2,           ARMA,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           ARMB,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           FR,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           BR,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           FL,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           BL,            tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Controller 1/2, Stick L/R, Axis X/Y
#define C1LX vexRT[Ch4]
#define C1LY vexRT[Ch3]
#define C1RX vexRT[Ch1]
#define ARMUP vexRT[Btn6U]
#define ARMDOWN vexRT[ChBtn6D]

task main()
{
	// User control code here, inside the loop

	while (true)
	{
		// This is the main execution loop for the user control program.
		// Each time through the loop your program should update motor + servo
		// values based on feedback from the joysticks.

		// ........................................................................
		// Insert user code here. This is where you use the joystick values to
		// update your motors, etc.
		// ........................................................................

		//Holonomic Drive
		// Y component, X component, Rotation
		motor[FL] = -C1LY - C1LX - C1RX;
		motor[FR] =  C1LY - C1LX - C1RX;
		motor[BR] =  C1LY + C1LX - C1RX;
		motor[BL] = -C1LY + C1LX - C1RX;

		//Arm UP
		if(vexRT[Btn6U] == 1)
		{
			motor[ARMA] = 127;
			motor[ARMB] = 127;
		}
		//Arm Down
		else if(vexRT[Btn6D] == 1)
		{
			motor[ARMA] = -127;
			motor[ARMB] = -127;
		}
		//Arm Halt
		else{
			motor[ARMA] = 0;
			motor[ARMB] = 0;
		}

		// Motor values can only be updated every 20ms
		wait10Msec(2);

	}

}
