#pragma config(Sensor, in1,    POT,            sensorPotentiometer)
#pragma config(Sensor, in2,    GYRO,           sensorNone)
#pragma config(Motor,  port2,           ARMA,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           ARMB,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           FR,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           BR,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           FL,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           BL,            tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// Controller 1/2, Stick L/R, Axis X/Y
#define C1LX vexRT[Ch4]
#define C1LY vexRT[Ch3]
#define C1RX vexRT[Ch1]
#define ARMUP vexRT[Btn6U]
#define ARMDOWN vexRT[ChBtn6D]

#define downPOS 2800
#define upPOS 1800
#define chuckPOS 875

int armMode = 0;

float target, //the potentiometer value you want
error, //the difference between target and current
proportionalCoefficient, //what you multiply error by to get motor power
proportional, //P term, what you set motors to
motorPower; //what you set the motors to

//Task to Manage Arm Position
task runArm()
{
	target = downPOS;
	proportionalCoefficient = 0.5;

	while (true)
	{
		//ENABLE PID
		if(armMode==1){
			error = target - SensorValue[POT];
			proportional = error * proportionalCoefficient;
			motorPower = proportional;
			motor[ARMA] = motorPower;
			motor[ARMB] = motorPower;
		}
		//DISABLE PID
		else if(armMode==0){
			//Arm UP
			if(vexRT[Btn5U] == 1)
			{
				//Soft Limit For Going UP
				if(SensorValue[POT]>chuckPOS){
					motor[ARMA] = -50;
					motor[ARMB] = -50;
				}
				else{
					motor[ARMA] = 0;
					motor[ARMB] = 0;
				}
			}
			//Arm Down
			else if(vexRT[Btn5D] == 1)
			{
				//Soft Limit For Going DOWN
				if(SensorValue[POT]<downPOS){
					motor[ARMA] = 50;
					motor[ARMB] = 50;
				}
				else{
					motor[ARMA] = 0;
					motor[ARMB] = 0;
				}
			}
			//Arm Stop
			else{
				motor[ARMA] = 0;
				motor[ARMB] = 0;
				target = SensorValue[POT];
				armMode = 1;
			}
			// Motor values can only be updated every 20ms
			wait1Msec(20);
		}
	}
}

//Holonomic Drive using 3 Inputs
void holonomicDrive(int Y1,int X1,int X2)
{
	// Y component, X component, Rotation
	motor[FL] = -Y1 - X1 - X2;
	motor[FR] =  Y1 - X1 - X2;
	motor[BR] =  Y1 + X1 - X2;
	motor[BL] = -Y1 + X1 - X2;
}

task main()
{
	// User control code here, inside the loop
	startTask(runArm);
	//Set arm mode to enable PID
	armMode = 1;

	//Create "deadzone" variables.
	int X2 = 0, Y1 = 0, X1 = 0, threshold = 30;

	while (true)
	{
		// This is the main execution loop for the user control program.
		// Each time through the loop your program should update motor + servo
		// values based on feedback from the joysticks.

		// ........................................................................
		// Insert user code here. This is where you use the joystick values to
		// update your motors, etc.
		// ........................................................................

		//Holonomic Drive Deadzone
		if(abs(C1LY) > threshold){
			Y1 = C1LY;
		}
		else{
			Y1 = 0;
		}
		if(abs(C1LX) > threshold){
			X1 = C1LX;
		}
		else{
			X1 = 0;
		}
		if(abs(C1RX) > threshold){
			X2 = C1RX;
		}
		else{
			X2 = 0;
		}

		//Holonomic Drive Function
		holonomicDrive(Y1,X1,X2);

		//Arm CHUCK
		if(vexRT[Btn7U] == 1)
		{
			target = chuckPOS;
		}
		//Arm UP
		else if(vexRT[Btn7L] == 1)
		{
			target = upPOS;
		}
		//Arm Down
		else if(vexRT[Btn7D] == 1)
		{
			target = downPOS;
		}

		//Manual Operation of Arm
		if(vexRT[Btn5U] == 1)
		{
			armMode = 0;
		}
		else if(vexRT[Btn5D] == 1)
		{
			armMode = 0;
		}

		// Motor values can only be updated every 20ms
		wait1Msec(20);

	}

}
